USE [master]
GO

WHILE EXISTS(select NULL from sys.databases where name='QLDL')
BEGIN
    DECLARE @SQL varchar(max)
    SELECT @SQL = COALESCE(@SQL,'') + 'Kill ' + Convert(varchar, SPId) + ';'
    FROM MASTER..SysProcesses
    WHERE DBId = DB_ID(N'QLDL') AND SPId <> @@SPId
    EXEC(@SQL)
    DROP DATABASE [QLDL]
END
GO

/* Collation = SQL_Latin1_General_CP1_CI_AS */
CREATE DATABASE [QLDL]
GO

USE [QLDL]
GO

USE [QLDL]
GO

/****** Object:  Table [dbo].[DAILY]    Script Date: 7/2/2018 12:43:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DAILY](
	[MaDaiLy] [nvarchar](50) NOT NULL,
	[TenDaiLy] [nvarchar](50) NULL,
	[MaLoaiDaiLy] [nvarchar](50) NULL,
	[DienThoai] [nvarchar](50) NULL,
	[DiaChi] [nvarchar](50) NULL,
	[MaQuan] [nvarchar](50) NULL,
	[NgayTiepNhan] [datetime2](7) NULL,
	[Email] [nvarchar](50) NULL,
	[NoCuaDaiLy] [nvarchar](50) NULL,
 CONSTRAINT [PK_DAILY] PRIMARY KEY CLUSTERED 
(
	[MaDaiLy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DAILY]  WITH CHECK ADD  CONSTRAINT [FK_DAILY_LOAIDAILY] FOREIGN KEY([MaLoaiDaiLy])
REFERENCES [dbo].[LOAIDAILY] ([MaLoaiDaiLy])
GO

ALTER TABLE [dbo].[DAILY] CHECK CONSTRAINT [FK_DAILY_LOAIDAILY]
GO

ALTER TABLE [dbo].[DAILY]  WITH CHECK ADD  CONSTRAINT [FK_DAILY_QUAN] FOREIGN KEY([MaQuan])
REFERENCES [dbo].[QUAN] ([MaQuan])
GO

ALTER TABLE [dbo].[DAILY] CHECK CONSTRAINT [FK_DAILY_QUAN]
GO

USE [QLDL]
GO

/****** Object:  Table [dbo].[CHITIETPHIEUXUAT]    Script Date: 7/2/2018 12:43:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHITIETPHIEUXUAT](
	[MaChiTietPhieuXuat] [nvarchar](50) NOT NULL,
	[MaPhieuXuat] [nvarchar](50) NULL,
	[MaMatHang] [nvarchar](50) NULL,
	[MaDonViTinh] [nvarchar](50) NULL,
	[SoLuongXuat] [nvarchar](50) NULL,
	[DonGiaXuat] [nvarchar](50) NULL,
	[ThanhTien] [nvarchar](50) NULL,
 CONSTRAINT [PK_CHITIETPHIEUXUAT] PRIMARY KEY CLUSTERED 
(
	[MaChiTietPhieuXuat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUXUAT_DONVITINH] FOREIGN KEY([MaDonViTinh])
REFERENCES [dbo].[DONVITINH] ([MaDonViTinh])
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT] CHECK CONSTRAINT [FK_CHITIETPHIEUXUAT_DONVITINH]
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUXUAT_MATHANG] FOREIGN KEY([MaMatHang])
REFERENCES [dbo].[MATHANG] ([MaMatHang])
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT] CHECK CONSTRAINT [FK_CHITIETPHIEUXUAT_MATHANG]
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUXUAT_PHIEUXUAT] FOREIGN KEY([MaPhieuXuat])
REFERENCES [dbo].[PHIEUXUAT] ([MaPhieuXuat])
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT] CHECK CONSTRAINT [FK_CHITIETPHIEUXUAT_PHIEUXUAT]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[DONVITINH]    Script Date: 7/2/2018 12:44:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DONVITINH](
	[MaDonViTinh] [nvarchar](50) NOT NULL,
	[TenDonViTinh] [nvarchar](50) NULL,
 CONSTRAINT [PK_DONVITINH] PRIMARY KEY CLUSTERED 
(
	[MaDonViTinh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[LOAIDAILY]    Script Date: 7/2/2018 12:44:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAIDAILY](
	[MaLoaiDaiLy] [nvarchar](50) NOT NULL,
	[TenLoaiDaiLy] [nvarchar](50) NULL,
	[NoToiDa] [nvarchar](50) NULL,
 CONSTRAINT [PK_LOAIDAILY] PRIMARY KEY CLUSTERED 
(
	[MaLoaiDaiLy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[MATHANG]    Script Date: 7/2/2018 12:44:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATHANG](
	[MaMatHang] [nvarchar](50) NOT NULL,
	[TenMatHang] [nvarchar](50) NULL,
	[SoLuongTon] [nvarchar](50) NULL,
	[DonGiaBan] [nvarchar](50) NULL,
 CONSTRAINT [PK_MATHANG] PRIMARY KEY CLUSTERED 
(
	[MaMatHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[PHIEUTHU]    Script Date: 7/2/2018 12:44:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEUTHU](
	[MaPhieuThu] [nvarchar](50) NOT NULL,
	[MaDaiLy] [nvarchar](50) NULL,
	[NgayThuTien] [datetime2](7) NULL,
	[SoTienThu] [nvarchar](50) NULL,
 CONSTRAINT [PK_PHIEUTHU] PRIMARY KEY CLUSTERED 
(
	[MaPhieuThu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHIEUTHU]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHU_DAILY] FOREIGN KEY([MaDaiLy])
REFERENCES [dbo].[DAILY] ([MaDaiLy])
GO

ALTER TABLE [dbo].[PHIEUTHU] CHECK CONSTRAINT [FK_PHIEUTHU_DAILY]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[PHIEUXUAT]    Script Date: 7/2/2018 12:45:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEUXUAT](
	[MaPhieuXuat] [nvarchar](50) NOT NULL,
	[MaDaiLy] [nvarchar](50) NULL,
	[NgayLapPhieu] [datetime2](7) NULL,
	[TongTriGia] [int] NULL,
 CONSTRAINT [PK_PHIEUXUAT] PRIMARY KEY CLUSTERED 
(
	[MaPhieuXuat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUXUAT_DAILY] FOREIGN KEY([MaDaiLy])
REFERENCES [dbo].[DAILY] ([MaDaiLy])
GO

ALTER TABLE [dbo].[PHIEUXUAT] CHECK CONSTRAINT [FK_PHIEUXUAT_DAILY]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[QUAN]    Script Date: 7/2/2018 12:45:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QUAN](
	[MaQuan] [nvarchar](50) NOT NULL,
	[TenQuan] [nvarchar](50) NULL,
 CONSTRAINT [PK_QUAN] PRIMARY KEY CLUSTERED 
(
	[MaQuan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [QLDL]
GO

/****** Object:  Table [dbo].[THAMSO]    Script Date: 7/2/2018 12:45:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[THAMSO](
	[SoLuongDaiLyToiDa] [int] NULL
) ON [PRIMARY]
GO


